<?php
// Function to modify the Yoast SEO title
function custom_yoast_seo_title($title) {
    // Check if the current page is using the example-template
    if (is_page_template('page-templates/template-example.php')) {
        // Get the current page title
        $page_title = get_the_title();
        
        // Construct the new title
        $new_title = 'Example title with h1' . $location . ' ☛ write something cool here';
        
        return $new_title;
    }
    
    // If not using the example-template, return the original title generated by Yoast SEO
    return $title;
}
add_filter('wpseo_title', 'custom_yoast_seo_title', 10, 1);
